apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-17T08:00:01Z"
  generation: 1
  labels:
    app: springbootdemoapp
  name: springbootdemoapp
  namespace: default
  resourceVersion: "62669"
  uid: 083212f6-b9bd-4269-ad96-3ae2cb260fc6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springbootdemoapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springbootdemoapp
    spec:
      containers:
        - image: snehangka/configmap-demo
          imagePullPolicy: Always
          name: configmap-demo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: hot-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-06-17T08:00:03Z"
      lastUpdateTime: "2022-06-17T08:00:03Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-06-17T08:00:01Z"
      lastUpdateTime: "2022-06-17T08:00:03Z"
      message: ReplicaSet "springbootdemoapp-677b7dd56d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
